# ワークフローの名前
name: Update Spotify Playlist

# 実行のきっかけ
on:
  schedule:
    # cron形式で「5分ごと」に実行
    - cron: '*/5 * * * *'
  # GitHubの画面から手動で実行するボタンも表示
  workflow_dispatch:

# 実行する一連の作業
jobs:
  run-script:
    # Ubuntuの最新環境で実行
    runs-on: ubuntu-latest

    # 実行する手順
    steps:
      # 1. リポジトリのコードをサーバーにコピー
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Python 3.10 の環境を準備
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 3. 必要なライブラリをインストール
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install spotipy

      # 4. Pythonスクリプトを実行
      - name: Run Python script
        env:
          # Settings > Secrets で登録した情報を環境変数として渡す
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          playlist_id: ${{ secrets.PLAYLIST_ID }}
          Japanese_playlist_id: ${{ secrets.JAPANESE_PLAYLIST_ID }}
        run: python main2.py 